---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: lab
description: This is where I will be testing new butrelinux features

base-image: quay.io/centos-bootc/centos-bootc
image-version: c10s
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - dnf config-manager --set-enabled crb
      - dnf install -y epel-release

  - type: nix
    source: local
    flavor: upstream 
    nix-version: latest
#    experimental-features: [nix-command, flakes]
    build-users: 32
    selinux: true
    extra-conf: |
      trusted-users = root @wheel

  - type: dnf
    install:
      packages:
        - kde-partitionmanager
        - krfb
        - krdc
        - khelpcenter
        - policycoreutils
        - policycoreutils-python-utils
        - policycoreutils-devel
        - selinux-policy-targeted
        - libsemanage
        - plasma-desktop
        - plasma-workspace-wayland
        - kde-settings-plasma
        - flatpak-kcm
        - kscreen
        - kinfocenter
        - sddm
        - sddm-kcm
        - sddm-breeze
        - polkit-kde
        - plasma-nm
        - plasma-disks
        - plasma-browser-integration
        - kde-connect
        - bluedevil
        - dolphin
        - kate
        - konsole
        - kio-admin
        - ark
        - spectacle
        - okular
        - plasma-systemmonitor
        - kde-gtk-config
        - kcalc
        - micro
        - btop
        - htop
        - xdg-desktop-portal-kde
        - firefox
        - powerdevil
        - tuned
        - tuned-ppd
        - tuned-profiles-atomic
        - lm_sensors
        - earlyoom
        
  - type: dnf
    install:
      install-weak-deps: false
      packages:
        - plasma-discover
        - plasma-discover-flatpak
        - plasma-discover-libs
        - plasma-discover-kns

  - type: kargs
    kargs:
      - amdgpu.ppfeaturemask=0xffffffff
      - split_lock_detect=off

  - type: systemd
    system:
      enabled:
        - sddm.service
        - tuned.service
        - tuned-ppd.service
        - earlyoom.service
      disabled:
        - nfs-client.target
      masked:
        - rpcbind.service
        - rpcbind.socket
        - systemd-oomd.service
        - system-flatpak-setup.timer
        - systemd-resolved.service

  - type: systemd
    system:
      disabled:
        - nfs-client.target
      masked:
        - rpcbind.service
        - rpcbind.socket

  - type: fonts
    fonts:
      nerd-fonts:
       - JetBrainsMono
       - NerdFontsSymbolsOnly
       - Noto

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
