---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: lab
description: This is where I will be testing new butrelinux features

base-image: quay.io/centos-bootc/centos-bootc
image-version: c10s
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: nix
    source: local
    flavor: upstream 
    nix-version: 2.23.0
#    experimental-features: [nix-command, flakes]
    build-users: 32
    selinux: true
    extra-conf: |
      trusted-users = root @wheel
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
